### PR TITLE
add linting for front matter yaml

### PR DESCRIPTION
**Pull request by alasdairwilson**
https://github.com/alasdairwilson/front-matter-lint  custom gh action to check front matters in the markdown

### CODE REVIEW

**Review by martinjrobins — APPROVED** [review]
thanks @alasdairwilson this is great. In the future it would be great to add more checks (e.g. check that the dependsOn links are valid, check the markdown syntax etc). Where would this be done, in your action or in a separate action?

**Comment by alasdairwilson** [comment]
> thanks @alasdairwilson this is great. In the future it would be great to add more checks (e.g. check that the dependsOn links are valid, check the markdown syntax etc). Where would this be done, in your action or in a separate action?

If we want to lint markdown we could use an out of the box solution (markdownlint) that I already use locally and would take very little time to setup an action for:

I just ran it on the course material and, the markdown is very badly conforming so it would be a ginormous diff but I can do that if you like! We would probably ignore line length and the initial heading requirement (which clashes with the frontmatter title field anyway). Personally I like 1 sentence per md line rather than a column limit too to make editing the md in the future easier (not constantly having to manually word wrap  when making additions which makes the diff messy). I am not sure if there is a rule that could enforce this though.

This one I made for this PR is pretty universal for any front matters  in markdown and a solution didn't seem to pre-exist,, some of the other things that would come in handy (dependson very much so) might be a bit more Gutenberg specific.

For these gutenberg specific things: we could probably make a separate repo for each action, or for a "gutenberg actions" sort of repo on the oxrse org that runs them all. I don't think either is a bad answer. We could adjust the existing action I made here but then it stops being universally applicable.

**Comment by alasdairwilson** [comment]
also I don't know why this didn't run the CI, maybe because I don't have rights but: 

https://github.com/alasdairwilson/course-material/actions/runs/9383749935/job/25838070184#step:3:7

Is the workflow running.

**Comment by martinjrobins** [comment]
I quite like the idea of separate generic actions that can be reused. If you can do another one for the markdown that would be great! I'll merge this in for now

**Pull request merged**
