### PR TITLE
Only lint on push to main

### PR DESCRIPTION
**Pull request by fcooper8472**
Prevent the workflow running twice every time a push updates a PR.

### CODE REVIEW

**Review by martinjrobins — CHANGES_REQUESTED** [review]
does this turn off the checks in PRs? (I ask cause there are no checks on your PR)

**Comment by fcooper8472** [comment]
> does this turn off the checks in PRs? (I ask cause there are no checks on your PR)

No: it will still check on PR, but, the check is only triggered if a *.md file is changed, which is why it didn't run on this PR.

**Comment by fcooper8472** [comment]
I really should get Alasdair to review this one, but it looks like he's not in the organisation!

**Review by martinjrobins — APPROVED** [review]
ahh ok :)

**Pull request merged**
